
services:
  fliptrend-mysql:
    image: mysql
    restart: always
    container_name: "fliptrend-mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3310:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql
      - fliptrend-mysql-data:/var/lib/mysql


volumes:
  fliptrend-mysql-data: